version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: arduino_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: arduinolog
      POSTGRES_USER: max
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: