# Server Port Configuration
server.port=8085

# PostgreSQL Datasource Settings (Matches your Docker credentials)
spring.datasource.url=jdbc:postgresql://localhost:5432/arduinolog
spring.datasource.username=max
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Automation Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect